### ISSUE TITLE
A couple of warnings when compiling.

### ISSUE THREAD

**Issue by calroc** [josephg/librope#7]
Hopefully this is nothing but I ran make and got two warnings (this is on Ubuntu 16.04).  Compilation seems fine, the test program works.

> $ git clone https://github.com/josephg/librope.git
> Cloning into 'librope'...
> remote: Counting objects: 297, done.
> remote: Total 297 (delta 0), reused 0 (delta 0), pack-reused 297
> Receiving objects: 100% (297/297), 91.82 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (163/163), done.
> Checking connectivity... done.
> 
> $ cd librope/
> 
> ~/librope$ make
> cc -O2 -Wall -I. -std=c99 rope.c -c -o rope.o
> rope.c: In function ‘random_height’:
> rope.c:169:44: warning: implicit declaration of function ‘random’ [-Wimplicit-function-declaration]
>    while(height < (ROPE_MAX_HEIGHT - 1) && (random() % 100) < ROPE_BIAS) {
>                                             ^
> rope.c: In function ‘rope_insert’:
> rope.c:572:7: warning: ‘num_end_chars’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>        insert_at(r, iter, &e->str[offset_bytes], num_end_bytes, num_end_chars);
>        ^
> rope.c:532:12: note: ‘num_end_chars’ was declared here
>      size_t num_end_chars, num_end_bytes = e->num_bytes - offset_bytes;
>             ^
> ar rcs librope.a rope.o
>

**Comment by josephg** [comment]
Thanks. The second of those warnings is fine. The first we should fix - and use `ar4_random` on Mac, and whatever else on other systems. If you want to put together a PR I’ll merge it.

**Comment by josephg** [comment]
Closing issue due to lack of followup
